name: Deploy to VM
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update Service
        run: |
          cd ~/PEI/WaitTime-Service
          git pull origin main
          cd ..
          docker compose up -d --build waittime-service