name: Deploy to VM
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update Service
        run: |
          cd ~/PEI/RUA-Backend-Services/WaitTime-Service
          git checkout main
          git pull origin main --rebase
          cd ~/PEI/RUA-Backend-Services
          docker compose up -d --build waittime-service